stages:
  - Test
  - Static Analysis

variables:
  VENV_DIR: $CI_PROJECT_DIR/../venv-pyFstat
  INSTALLER_DIR: $CI_PROJECT_DIR/install-cw-software

pytest:
  stage: Test
  tags: [ pyFstat ]
  before_script:
    - python3 -m venv $VENV_DIR
    - source ${VENV_DIR}/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install lalsuite
    - pip install pytest
    - export LAL_DATA_PATH=$HOME/ephemeris
    - export LALPULSAR_DATADIR=$LAL_DATA_PATH

  script:
    - pip install -e $CI_PROJECT_DIR
      # make sure to test *installed* version of pyFstat
    - (cd .. && pytest $CI_PROJECT_DIR/tests.py --log-file=$CI_PROJECT_DIR/tests.log)

  artifacts:
    paths:
      - ./*.log
    name: testlogs
    when: always
    expire_in: 24h

.static:
  stage: Static Analysis
  script:
    - source ${VENV_DIR}/bin/activate
    - black --check .
    # - flake8 .  ## not ready
